// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/worker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerEngine_Execute_FullMethodName     = "/worker.WorkerEngine/Execute"
	WorkerEngine_GetStats_FullMethodName    = "/worker.WorkerEngine/GetStats"
	WorkerEngine_HealthCheck_FullMethodName = "/worker.WorkerEngine/HealthCheck"
)

// WorkerEngineClient is the client API for WorkerEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerEngineClient interface {
	Execute(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EngineStats, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type workerEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerEngineClient(cc grpc.ClientConnInterface) WorkerEngineClient {
	return &workerEngineClient{cc}
}

func (c *workerEngineClient) Execute(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, WorkerEngine_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerEngineClient) GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EngineStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EngineStats)
	err := c.cc.Invoke(ctx, WorkerEngine_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerEngineClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, WorkerEngine_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerEngineServer is the server API for WorkerEngine service.
// All implementations must embed UnimplementedWorkerEngineServer
// for forward compatibility.
type WorkerEngineServer interface {
	Execute(context.Context, *TaskRequest) (*TaskResponse, error)
	GetStats(context.Context, *Empty) (*EngineStats, error)
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedWorkerEngineServer()
}

// UnimplementedWorkerEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerEngineServer struct{}

func (UnimplementedWorkerEngineServer) Execute(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedWorkerEngineServer) GetStats(context.Context, *Empty) (*EngineStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedWorkerEngineServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedWorkerEngineServer) mustEmbedUnimplementedWorkerEngineServer() {}
func (UnimplementedWorkerEngineServer) testEmbeddedByValue()                      {}

// UnsafeWorkerEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerEngineServer will
// result in compilation errors.
type UnsafeWorkerEngineServer interface {
	mustEmbedUnimplementedWorkerEngineServer()
}

func RegisterWorkerEngineServer(s grpc.ServiceRegistrar, srv WorkerEngineServer) {
	// If the following call panics, it indicates UnimplementedWorkerEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerEngine_ServiceDesc, srv)
}

func _WorkerEngine_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerEngineServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerEngine_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerEngineServer).Execute(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerEngine_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerEngineServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerEngine_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerEngineServer).GetStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerEngine_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerEngineServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerEngine_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerEngineServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerEngine_ServiceDesc is the grpc.ServiceDesc for WorkerEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.WorkerEngine",
	HandlerType: (*WorkerEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _WorkerEngine_Execute_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _WorkerEngine_GetStats_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _WorkerEngine_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/worker.proto",
}
